package ChipsRPG;


    public enum EntityTypes {
        CHIP, PLAYER, WALL, REDKEY, BLUEKEY, GREENKEY, YELLOWKEY, REDDOOR, BLUEDOOR, GREENDOOR, YELLOWDOOR,
        ENDZONE, ICE, ICECORNERTR,ICECORNERTL,ICECORNERBR,ICECORNERBL, FIRE, ICEBOOTS, FIREBOOTS, WATER, WATERBOOTS,
        SPEEDUP,SPEEDDOWN,SPEEDLEFT,SPEEDRIGHT,SUCKERBOOTS,DIRTBLOCK, QUESTIONBLOCK,

        TANKUP, TANKLEFT, TANKDOWN, TANKRIGHT, TANKACTIVATOR,

        RETRACTEDWALL,

        BUG, ENEMYTEST,
    }

